"""initial schema

Revision ID: 5c4e50629ef1
Revises: 
Create Date: 2026-09-17 16:30:05.544429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c4e50629ef1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('effects_flow',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('input_gain', sa.Float(), nullable=True),
    sa.Column('output_gain', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_library',
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('download_url', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setlist',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gig_date', sa.String(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('lyrics_url', sa.String(), nullable=True),
    sa.Column('tab_url', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('effect_model',
    sa.Column('model_library_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('tone3000_id', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['model_library_id'], ['model_library.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('led_display',
    sa.Column('effects_flow_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('colour', sa.String(), nullable=True),
    sa.Column('brightness', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['effects_flow_id'], ['effects_flow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('effects_flow_id')
    )
    op.create_table('setlist_song',
    sa.Column('setlist_id', sa.String(length=36), nullable=False),
    sa.Column('song_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['setlist_id'], ['setlist.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setlist_id', 'position')
    )
    op.create_table('song_footswitch',
    sa.Column('song_id', sa.String(length=36), nullable=False),
    sa.Column('effects_flow_id', sa.String(length=36), nullable=False),
    sa.Column('switch_slot', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('switch_slot BETWEEN 1 AND 4', name='ck_song_footswitch_slot_range'),
    sa.ForeignKeyConstraint(['effects_flow_id'], ['effects_flow.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('song_id', 'switch_slot')
    )
    op.create_table('effect',
    sa.Column('effects_flow_id', sa.String(length=36), nullable=False),
    sa.Column('effect_model_id', sa.String(length=36), nullable=False),
    sa.Column('chain_position', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['effect_model_id'], ['effect_model.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['effects_flow_id'], ['effects_flow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('effects_flow_id', 'chain_position')
    )
    op.create_table('effect_params',
    sa.Column('effect_id', sa.String(length=36), nullable=False),
    sa.Column('param_name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('max', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['effect_id'], ['effect.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('effect_id', 'param_name')
    )
    op.create_table('footswitch_map',
    sa.Column('effects_flow_id', sa.String(length=36), nullable=False),
    sa.Column('switch_number', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_effect_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['effects_flow_id'], ['effects_flow.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_effect_id'], ['effect.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('effects_flow_id', 'switch_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('footswitch_map')
    op.drop_table('effect_params')
    op.drop_table('effect')
    op.drop_table('song_footswitch')
    op.drop_table('setlist_song')
    op.drop_table('led_display')
    op.drop_table('effect_model')
    op.drop_table('song')
    op.drop_table('setlist')
    op.drop_table('model_library')
    op.drop_table('effects_flow')
    # ### end Alembic commands ###
